name: Build and Deploy to Subdomain Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Deploy to subdomain repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: khanhdo16/chatgpt.khanhdo16.github.io
          publish_branch: main
          publish_dir: ./dist   # or your build output folder
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
